spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jeju
    password: jejupw
    url: jdbc:mysql://localhost:3306/jeju